services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shrikant
      - MONGO_INITDB_ROOT_PASSWORD=shrikant
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=shrikant
      - ME_CONFIG_MONGODB_ADMINPASSWORD=shrikant
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}